In [1]:
import numpy as np

In [2]:
# Creating an empty array
a = np.array([])
a

array([], dtype=float64)

In [3]:
a = ([1,2,3,4])

In [9]:
np.array(a)

array([1, 2, 3, 4])

In [10]:
type(a)

numpy.ndarray

In [12]:
# size method in numpy
a.size                     

4

In [13]:
# shape method
a.shape

(4,)

In [14]:
# ndim method
a.ndim

1

In [18]:
# Lets convert this 1D array into 2D array.
# We will use reshape function to reshape the size of array

b = a.reshape(2,2)

In [19]:
b

array([[1, 2],
       [3, 4]])

In [20]:
b.ndim                # The array is converted into a 2D array.

2

In [25]:
# 3D array 
c = np.array([[[1,2,3],[3,4,4]],[[7,7,7],[2,3,4]]])

In [26]:
c

array([[[1, 2, 3],
        [3, 4, 4]],

       [[7, 7, 7],
        [2, 3, 4]]])

In [27]:
c.ndim

3

In [28]:
# arange
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [43]:
np.arange(12,1,-2).reshape(3,2)

array([[12, 10],
       [ 8,  6],
       [ 4,  2]])