Importing Numpy array

In [1]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [5]:
arr = np.array([1,2,3,4,5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr[4]

5

In [8]:
type(arr)                                 # ndarray means number dimension array.

numpy.ndarray

In [9]:
arr.size

5

In [10]:
arr.shape

(5,)

Arrays can be of n dimensions

In [5]:
n = [[1,2,3],[2,3,4]]
n

[[1, 2, 3], [2, 3, 4]]

In [13]:
type(n)

list

In [6]:
arr2 = np.array(n)

In [19]:
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
print("The dimension of Array",arr2.ndim)

The dimension of Array 2


In [8]:
print("The size of array is",arr2.size)

The size of array is 6


In [9]:
print("The shape of array is",arr2.shape)

The shape of array is (2, 3)


In [10]:
print("The type of structure is",type(arr2))

The type of structure is <class 'numpy.ndarray'>


In [11]:
arr3 = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[9,8,7]]])

In [17]:
print(arr3)
arr3.shape

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [9 8 7]]]


(2, 2, 3)

Converting a 3D array into 2D and 1D array.

In [18]:
# reshape - Use for reshaping the dimensions of array for ex. changing the no. of blocks,rows and columns.

In [20]:
arr3.reshape(2,6)

array([[1, 2, 3, 2, 3, 4],
       [3, 4, 5, 9, 8, 7]])

In [21]:
arr3                             # It will not commit the reshape if you did not store it in a variable
                                 # So if you want to permanantly commit the changes you should store it in a new variable.

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [9, 8, 7]]])

In [22]:
n_arr = arr3.reshape(2,6)                               # Converted to 2D array

In [23]:
n_arr

array([[1, 2, 3, 2, 3, 4],
       [3, 4, 5, 9, 8, 7]])

In [24]:
arr_1 = arr3.reshape(12)                               # Converted to 1D array

In [26]:
arr_1

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 9, 8, 7])

### arange

return evenly spaced values with in a given interval

In [27]:
np.arange(12)    # Starts from 0 and excludes end value.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a = np.arange(12)

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.arange(0,11)   # start , end

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.arange(0,11,2)  # start,end,step

array([ 0,  2,  4,  6,  8, 10])

In [32]:
np.arange(40,10,-2)

array([40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12])

In [33]:
np.arange(0,11,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

## Linespace

In [2]:
a = np.linspace(1,10,6)

In [3]:
a

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [7]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [12]:
np.linspace(1,5,retstep=True)        # retstep ~ return step computed by linspace

(array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
        1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
        1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
        2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
        2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
        3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
        3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
        3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
        4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
        4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ]),
 0.08163265306122448)

In [14]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [15]:
np.linspace(0,100,10,retstep=True)

(array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
         44.44444444,  55.55555556,  66.66666667,  77.77777778,
         88.88888889, 100.        ]),
 11.11111111111111)

### eye   
To create an identity matrix.

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Broadcasting in Numpy.

The ability to access each and every element of an array is known as Broadcasting.

In [9]:
li = [1,2,3,4,5]
mul = li*3
print(mul)                       # In list if we multiply any list by any number it will not multiply the values instead it will multiply the length of the list.


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [11]:
arr = np.array(li)
mul = arr*3                     # But in array it will multiply each value.
print(mul)

[ 3  6  9 12 15]


In [14]:
one = np.ones((2,2))
one

array([[1., 1.],
       [1., 1.]])

In [15]:
one*2

array([[2., 2.],
       [2., 2.]])

In [16]:
one*2+1

array([[3., 3.],
       [3., 3.]])

In [22]:
big_one = np.array(one*9-1,dtype = 'int64')

In [23]:
big_one

array([[8, 8],
       [8, 8]], dtype=int64)

## Copy function

In [2]:
arr1 = np.arange(1,16)

In [3]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr1[:10]=30

In [5]:
arr1

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 11, 12, 13, 14, 15])

In [6]:
arr2 = arr1.copy()

In [7]:
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 11, 12, 13, 14, 15])

In [10]:
arr2[11:]=99
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 11, 99, 99, 99, 99])

In [9]:
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 11, 99, 99, 99, 99])

## Random Number Generation  
Numpy also has lots of ways to generate random numbers.

In [11]:
import numpy as np

In [14]:
np.random.rand()

0.41566314069694077

In [17]:
arr = np.random.rand(10)     # Rand function always gives values from 0 to 1

In [16]:
arr

array([0.89427225, 0.40640198, 0.8928255 , 0.34044613, 0.77569731,
       0.62342462, 0.65097437, 0.4612455 , 0.5839884 , 0.78976931])

In [25]:
arr.reshape(5,2) # Creating array from uniform distribution. i.e 0 to 1

array([[0.05185008, 0.40986481],
       [0.23303078, 0.1876538 ],
       [0.76462431, 0.81599814],
       [0.36950587, 0.93008748],
       [0.51780563, 0.07760663]])

In [22]:
np.random.rand(2,4)

array([[0.024255  , 0.004172  , 0.84121702, 0.4035705 ],
       [0.77827835, 0.33833313, 0.2652468 , 0.7642098 ]])

### Randn  
Creating arrays from normal distribution.  
i.e. -1 to 1.

In [24]:
np.random.randn(2,2)

array([[-0.35737499,  0.26233585],
       [ 0.0707389 ,  1.11289533]])

### Randint  
returns any random integers from specified range .

In [26]:
np.random.randint(1,100,10)

array([93, 55, 54, 28, 22, 10, 85, 35, 79, 44])

In [30]:
arr = np.random.randint(1,100,10)
arr

array([65, 34, 19, 32, 28, 64, 14, 76, 14, 68])

In [31]:
arr.max()

76

In [32]:
arr.min()

14

In [34]:
arr.argmin() # index location of lowest number

6

In [37]:
arr.argmax() # index location of highest number.

7