In [1]:
import numpy as np

In [4]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## Bracket indexing and selecting

In [7]:
b = np.arange(10,100,5)
b

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [8]:
b[-2]

90

In [9]:
b[9]

55

In [10]:
b[1:11:2]

array([15, 25, 35, 45, 55])

In [11]:
b[10:1:-2]

array([60, 50, 40, 30, 20])

In [13]:
b[-2:-10:-2]

array([90, 80, 70, 60])

## Filtering 

In [14]:
a = np.array([1,1012,15,100,23])
a

array([   1, 1012,   15,  100,   23])

In [15]:
a[1]

1012

In [17]:
a.dtype

dtype('int32')

In [18]:
a<100

array([ True, False,  True, False,  True])

In [20]:
a>100

array([False,  True, False, False, False])

In [21]:
a[4]

23

In [22]:
np.where(a<100)

array([False,  True, False, False, False])

In [23]:
np.where(a==100)

(array([3], dtype=int64),)

In [27]:
np.concatenate((a,[100,190,145]))

array([   1, 1012,   15,  100,   23,  100,  190,  145])

In [28]:
np.delete(a,1)

array([  1,  15, 100,  23])

In [29]:
a

array([   1, 1012,   15,  100,   23])

## Indexing 2D Array

In [30]:
ar = np.array([[1,2,3],[2,3,4]])

In [31]:
ar

array([[1, 2, 3],
       [2, 3, 4]])

In [32]:
ar[1,1]

3

In [33]:
ar[0,2]

3

In [36]:
ar[0:,:2]

array([[1, 2],
       [2, 3]])

In [37]:
ar

array([[1, 2, 3],
       [2, 3, 4]])

In [38]:
ar[:,1]

array([2, 3])

## Fancy Indexing

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order.

In [39]:
arr = np.arange(1,101)

In [40]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [45]:
arr = arr.reshape(10,10)

In [46]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [50]:
arr[3:8:2,3:8:2]

array([[34, 36, 38],
       [54, 56, 58],
       [74, 76, 78]])

In [52]:
arr[[2,5,9]]            # it will select all the rows on specific indexes

array([[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [53]:
arr[:,[1,2,4]]

array([[ 2,  3,  5],
       [12, 13, 15],
       [22, 23, 25],
       [32, 33, 35],
       [42, 43, 45],
       [52, 53, 55],
       [62, 63, 65],
       [72, 73, 75],
       [82, 83, 85],
       [92, 93, 95]])

In [54]:
arr[[6,2,9,1]]                   # Allows in any order.

array([[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]])