In [1]:
x = "Hey there!"

In [2]:
x.split()

['Hey', 'there!']

In [4]:
x.partition(" ")

('Hey', ' ', 'there!')

In [16]:
x[-6:8]

'ther'

In [17]:
print(x[0]+"ello"+x[3:])

Hello there!


### Numpy

In [18]:
import numpy as np

In [28]:
arr = np.array([1,2,3,4])

In [22]:
type(arr)

numpy.ndarray

In [25]:
arr.shape

(3,)

In [30]:
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [32]:
arr2 = np.append(arr,[2,3])

In [37]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [2, 3]])

In [39]:
arr3 = np.append(arr2,[[4,5],[6,9],[9,9]])

In [40]:
arr3

array([1, 2, 3, 4, 2, 3, 4, 5, 6, 9, 9, 9])

In [44]:
arr3.reshape(3,1,4)

array([[[1, 2, 3, 4]],

       [[2, 3, 4, 5]],

       [[6, 9, 9, 9]]])

In [61]:
arr3.shape

(12,)

In [62]:
n_arr = np.array([[[1,2],[2,3]],
                 [[3,3],[9,7]]])

In [63]:
n_arr.shape

(2, 2, 2)

In [64]:
n_arr

array([[[1, 2],
        [2, 3]],

       [[3, 3],
        [9, 7]]])

In [66]:
n_arr[0,1,1]

3

In [67]:
n_arr.ndim

3